### ISSUE TITLE
Optional Atlantis auto_plan on transitive module dependencies

### ISSUE THREAD

**Issue by vincenthsh** [vincenthsh/fogg#230]
## Current
 
If component `A` depends on:
1. Modules: `foo` & `bar`
2. Components: `B`

And component `B` depends on:
1. Modules: `baz`

Currently fogg generates Atlantis config as follows:

```yaml
projects:
- A:
    auto_plan:
    - ./
    - ../path/to/module/foo
    - ../path/to/module/bar

- B:
    auto_plan:
    - ./
    - ../path/to/module/baz
```

If module `baz` changes, component `B` is planned
If component `B` changes, component `A` is not planned

In some cases, when module `baz` or component `B` are changed, component `A` could have a diff which is not detected.

## Proposal:

- Optionally, Atlantis should autoplan component `A` if component `B` has changes
- Optionally, Atlantis should autoplan component `A` if module `baz` changes

Possible issues:
1. Changes in `B` haven't been applied, so atlantis autoplan on `A` may fail, however this could be more desirable than not detecting the diff in `A` and in such cases either manual intervention (targetted plan/apply or split PR) should handle this until Atlantis can manage it?

Expected Atlantis config (when feature is enabled):

```yaml
projects:
- A:
    auto_plan:
    - ../path/to/component/A
    - ../path/to/module/foo
    - ../path/to/module/bar
    # because A depends on B
    - ../path/to/component/B
    - ../path/to/module/baz

- B:
    auto_plan:
    - ../path/to/component/B
    - ../path/to/module/baz
```
